# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.producer.example.com:
  peer0.manufacturer.example.com:
  peer0.deliverer.example.com:
  peer0.retailer.example.com:
  caProducer:
  caManufacturer:
  caDeliverer:
  caRetailer:

networks:
  byfn:

services:

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - byfn

  peer0.producer.example.com:
    container_name: peer0.producer.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.producer.example.com
    networks:
      - byfn

  peer0.manufacturer.example.com:
    container_name: peer0.manufacturer.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.manufacturer.example.com
    networks:
      - byfn
      
  peer0.deliverer.example.com:
    container_name: peer0.deliverer.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.deliverer.example.com
    networks:
      - byfn
      
  peer0.retailer.example.com:
    container_name: peer0.retailer.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.retailer.example.com
    networks:
      - byfn
      
  caProducer:
    container_name: caProducer
    extends:
      file:  base/docker-compose-base.yaml
      service: caProducer
    networks:
      - byfn
      
  caManufacturer:
    container_name: caManufacturer
    extends:
      file:  base/docker-compose-base.yaml
      service: caManufacturer
    networks:
      - byfn
      
  caDeliverer:
    container_name: caDeliverer
    extends:
      file:  base/docker-compose-base.yaml
      service: caDeliverer
    networks:
      - byfn
      
  caRetailer:
    container_name: caRetailer
    extends:
      file:  base/docker-compose-base.yaml
      service: caRetailer
    networks:
      - byfn
      
      
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.producer.example.com:7051
      - CORE_PEER_LOCALMSPID=ProducerMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/producer.example.com/peers/peer0.producer.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/producer.example.com/peers/peer0.producer.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/producer.example.com/peers/peer0.producer.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/producer.example.com/users/Admin@producer.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.producer.example.com
      - peer0.manufacturer.example.com
      - peer0.deliverer.example.com
      - peer0.retailer.example.com
      - caProducer
      - caManufacturer
      - caDeliverer
      - caRetailer
    networks:
      - byfn
